name: Build ShahrFlow on Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on Windows with MSVC
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build the project
      run: cmake --build build --config Release

    - name: Copy runtime files
      shell: pwsh
      run: |
        Copy-Item resource/settings.json -Destination build/Release/ -Force
        if (-Not (Test-Path 'build/Release/shaders')) {
          New-Item -ItemType Directory -Path 'build/Release/shaders'
        }
        Copy-Item shaders/* -Destination build/Release/shaders/ -Recurse -Force

    - name: Prepare Output
      shell: cmd
      run: |
        mkdir -p ShahrFlow\ShahrFlow
        copy build\Release\ShahrFlow.exe ShahrFlow\ShahrFlow\
        copy build\Release\settings.json ShahrFlow\ShahrFlow\
        xcopy build\Release\shaders ShahrFlow\ShahrFlow\shaders\ /E /I /Y
      
    - name: Upload Executable and Assets
      uses: actions/upload-artifact@v4
      with:
        name: ShahrFlow
        path: 
          ShahrFlow/